### ISSUE TITLE
Rule file generation with MySql Database.

### ISSUE THREAD

**Issue by makotoitomeitetsucom** [R4ND3LL/EdmxRuler#10]
Konnichiwa (Hello) Mark.
I found another one.

I created entities from the MySqlDatabase with the command  "dotnet ef dbcontext scaffold".

A rule file was generated like below .

```
{
  "Name": "EfCoreContext",
  "PreserveCasingUsingRegex": false,
  "IncludeUnknownSchemas": true,
  "SplitEntityTypeConfigurations": false,
  "Schemas": [
    {
      "SchemaName": "",
      "IncludeUnknownTables": true,
      "IncludeUnknownViews": true,
      "Namespace": null,
      "Entities": [
        {
          "Name": "tables",
          "EntityName": "Table",
          "IncludeUnknownColumns": true,
          "Properties": [
            {
              "Name": "col1",
              "PropertyName": "Col1"
            }         ]
        }
      ]
    }
  ]
}
```

I tried the command "dotnet ef dbcontext scaffold" again.
The rule file was modified like below .

```
{
  "Name": "EfCoreContext",
  "PreserveCasingUsingRegex": false,
  "IncludeUnknownSchemas": true,
  "SplitEntityTypeConfigurations": false,
  "Schemas": [
    {
      "SchemaName": "",
      "IncludeUnknownTables": true,
      "IncludeUnknownViews": true,
      "Namespace": null,
      "Entities": [
        {
          "Name": "tables",
          "EntityName": "Table",
          "IncludeUnknownColumns": true,
          "Properties": [
            {
              "Name": "col1",
              "PropertyName": "Col1"
            }         ]
        }
      ]
    },
    {
      "SchemaName": "",
      "IncludeUnknownTables": true,
      "IncludeUnknownViews": true,
      "Namespace": null
    },
  ]
}
```

The part of below will be added with the command.
```
    {
      "SchemaName": "",
      "IncludeUnknownTables": true,
      "IncludeUnknownViews": true,
      "Namespace": null
    }
```
In the case of MySql, "SchemaName" will be empty.
When that property is empty, I think the section would be added.

Logs and providers are following.
```
EF Ruler v1.0.0.0 detected Entity Framework v7.0.2.0
EF Ruler resolved target assembly: EfCoreFirstStep
EF Ruler loaded 1 rule file(s).
Using ServerVersion '5.7.12-mysql'.
DbContext rule file written to EfCoreContext-rules.json
Updated EfCoreContext-rules.json in 16ms
```

```
<PackageReference Include="EntityFrameworkRuler.Design" Version="1.2.4">
<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.2">
<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.2">
<PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="7.0.0" />
```

**Comment by R4ND3LL** [comment]
While I don't have a MySql environment, I made changes to support empty schema names (it definitely was not supported before).

NuGet packages v1.2.13 has been published. Along with a new VSIX.   Let me know if that fixes this specific issue.

**Comment by makotoitomeitetsucom** [comment]
Hello Mark. And thank for your action.

I updated the version to v1.2.13 and tried to run the command  "dotnet ef dbcontext scaffold".

After that I got an error. 
The stack trace is following.

```
CoreFirstStepModel.Entities --force --no-onconfiguring
Build started...
Build succeeded.
EF Ruler v1.0.0.0 detected Entity Framework v7.0.2.0
EF Ruler resolved target assembly: EfCoreFirstStep
EF Ruler loaded 1 rule file(s).
Using ServerVersion '5.7.12-mysql'.
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.VisitTables(ModelBuilder modelBuilder, ICollection`1 tables)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.Castle.DynamicProxy.IInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.RelationalScaffoldingModelFactoryProxy.VisitTables(ModelBuilder modelBuilder, ICollection`1 tables)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel)
   at Castle.Proxies.RelationalScaffoldingModelFactoryProxy.VisitDatabaseModel_callback(ModelBuilder modelBuilder, DatabaseModel 
databaseModel)
   at Castle.Proxies.Invocations.RelationalScaffoldingModelFactory_VisitDatabaseModel.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.<>c__DisplayClass54_0.<Castle.DynamicProxy.IInterceptor.Intercept>g__BaseCall|2()
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel, Func`1 baseCall)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.Castle.DynamicProxy.IInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.RelationalScaffoldingModelFactoryProxy.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(DatabaseModel databaseModel, ModelReverseEngineerOptions options)
   at Castle.Proxies.RelationalScaffoldingModelFactoryProxy.Create_callback(DatabaseModel databaseModel, ModelReverseEngineerOptions options)
   at Castle.Proxies.Invocations.RelationalScaffoldingModelFactory_Create.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.<>c__DisplayClass54_0.<Castle.DynamicProxy.IInterceptor.Intercept>g__BaseCall|7(DatabaseModel databaseModel, ModelReverseEngineerOptions options2)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.Create(DatabaseModel databaseModel, ModelReverseEngineerOptions ops, Func`3 baseCall)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.Castle.DynamicProxy.IInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.RelationalScaffoldingModelFactoryProxy.Create(DatabaseModel databaseModel, ModelReverseEngineerOptions options)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.Create(DatabaseModel databaseModel, ModelReverseEngineerOptions ops)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at EntityFrameworkRuler.Design.Services.RuledReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, 
String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Value cannot be null. (Parameter 'key')
```

unfortunately it seems that still not working well...

**Comment by R4ND3LL** [comment]
Sorry for the issue.  Still without a MySql environment so unable to fully test, but I have modified the code again in v1.2.14.  Hopefully it works now.   Let me know.

**Comment by makotoitomeitetsucom** [comment]
Hello. I updated the version to 1.2.14.
![image](https://user-images.githubusercontent.com/25972784/215012116-9a4d4b9d-2f36-4b03-bcc9-f84674886f35.png)

And I encountered the same error.


```
Build started...
Build succeeded.
EF Ruler v1.0.0.0 detected Entity Framework v7.0.2.0
EF Ruler resolved target assembly: EfCoreFirstStep
EF Ruler loaded 1 rule file(s).
Using ServerVersion '5.7.12-mysql'.
System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at EntityFrameworkRuler.Design.Services.Models.ScaffoldedTableTracker.InitializeScope(IEnumerable`1 tables, DbContextRuleNode 
dbContextRuleNode)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.VisitTables(ModelBuilder modelBuilder, ICollection`1 tables)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.Castle.DynamicProxy.IInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.RelationalScaffoldingModelFactoryProxy.VisitTables(ModelBuilder modelBuilder, ICollection`1 tables)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel)
   at Castle.Proxies.RelationalScaffoldingModelFactoryProxy.VisitDatabaseModel_callback(ModelBuilder modelBuilder, DatabaseModel 
databaseModel)
   at Castle.Proxies.Invocations.RelationalScaffoldingModelFactory_VisitDatabaseModel.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.<>c__DisplayClass54_0.<Castle.DynamicProxy.IInterceptor.Intercept>g__BaseCall|2()
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel, Func`1 baseCall)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.Castle.DynamicProxy.IInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.RelationalScaffoldingModelFactoryProxy.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(DatabaseModel databaseModel, ModelReverseEngineerOptions options)
   at Castle.Proxies.RelationalScaffoldingModelFactoryProxy.Create_callback(DatabaseModel databaseModel, ModelReverseEngineerOptions options)
   at Castle.Proxies.Invocations.RelationalScaffoldingModelFactory_Create.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.<>c__DisplayClass54_0.<Castle.DynamicProxy.IInterceptor.Intercept>g__BaseCall|7(DatabaseModel databaseModel, ModelReverseEngineerOptions options2)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.Create(DatabaseModel databaseModel, ModelReverseEngineerOptions ops, Func`3 baseCall)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.Castle.DynamicProxy.IInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.RelationalScaffoldingModelFactoryProxy.Create(DatabaseModel databaseModel, ModelReverseEngineerOptions options)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.Create(DatabaseModel databaseModel, ModelReverseEngineerOptions ops)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at EntityFrameworkRuler.Design.Services.RuledReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, 
String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Value cannot be null. (Parameter 'key')
```

**Comment by R4ND3LL** [comment]
Found an issue with my string extension method for screening nulls (typo).  

v1.2.15 has the fix.

I scaffolded a MySql DB, however, in my case, the schema was not null.  So it wasn't an equivalent scenario.  It did generate/update the json file properly on multiple executions.

Hopefully this fixes it for you.

**Comment by makotoitomeitetsucom** [comment]
Hello Mark. 
I tried it again on version 1.2.16, and finally it worked fine!
Thank you for your great work.
