### ISSUE TITLE
System.ArgumentException: An item with the same key has already been added

### ISSUE THREAD

**Issue by MagicAndre1981** [R4ND3LL/EdmxRuler#22]
> The fix is to remove the name Firebird from the json schema file (in one spot):
> ![image](https://user-images.githubusercontent.com/65310488/225651547-ea67cf1b-a3ff-4a54-b80d-8d5d793bd78e.png)

_Originally posted by @R4ND3LL in https://github.com/R4ND3LL/EntityFrameworkRuler/issues/20#issuecomment-1472123339_

ok, I removed Firebird from schema and now I get an System.ArgumentException:

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: An item with the same key has already been added. Key: FOO
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
 at EntityFrameworkRuler.Design.Services.Models.DbContextRuleNode.Map(EntityTypeBuilder entityTypeBuilder, EntityRuleNode entityRule)
   at EntityFrameworkRuler.Design.Services.Models.EntityRuleNode.MapTo(EntityTypeBuilder builder, DatabaseTableNode databaseTable)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.ApplyEntityRules(ModelBuilder modelBuilder, EntityTypeBuilder entityTypeBuilder, DatabaseTable table, EntityRuleNode entityRuleNode)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.VisitTable(ModelBuilder modelBuilder, DatabaseTable table, Func`1 baseCall)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.Castle.DynamicProxy.IInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.RelationalScaffoldingModelFactoryProxy.VisitTable(ModelBuilder modelBuilder, DatabaseTable table)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.InvokeVisitTable(ModelBuilder modelBuilder, DatabaseTable table)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.<VisitTables>g__DoInvokeVisitTable|34_0(DatabaseTableNode table, EntityRuleNode entityRule, <>c__DisplayClass34_0& )
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.VisitTables(ModelBuilder modelBuilder, ICollection`1 tables)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.Castle.DynamicProxy.IInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.RelationalScaffoldingModelFactoryProxy.VisitTables(ModelBuilder modelBuilder, ICollection`1 tables)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel)
   at Castle.Proxies.RelationalScaffoldingModelFactoryProxy.VisitDatabaseModel_callback(ModelBuilder modelBuilder, DatabaseModel databaseModel)
   at Castle.Proxies.Invocations.RelationalScaffoldingModelFactory_VisitDatabaseModel.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.<>c__DisplayClass57_0.<Castle.DynamicProxy.IInterceptor.Intercept>g__BaseCall|2()
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel, Func`1 baseCall)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.Castle.DynamicProxy.IInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.RelationalScaffoldingModelFactoryProxy.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(DatabaseModel databaseModel, ModelReverseEngineerOptions options)
   at Castle.Proxies.RelationalScaffoldingModelFactoryProxy.Create_callback(DatabaseModel databaseModel, ModelReverseEngineerOptions options)
   at Castle.Proxies.Invocations.RelationalScaffoldingModelFactory_Create.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.<>c__DisplayClass57_0.<Castle.DynamicProxy.IInterceptor.Intercept>g__BaseCall|7(DatabaseModel databaseModel, ModelReverseEngineerOptions options2)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.Create(DatabaseModel databaseModel, ModelReverseEngineerOptions ops, Func`3 baseCall)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.Castle.DynamicProxy.IInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.RelationalScaffoldingModelFactoryProxy.Create(DatabaseModel databaseModel, ModelReverseEngineerOptions options)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.Create(DatabaseModel databaseModel, ModelReverseEngineerOptions ops)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at EntityFrameworkRuler.Design.Services.RuledReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluarlize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

I can't really share this EDMX from a real software, not the employee sample db (european data protection).

**Comment by MagicAndre1981** [comment]
ok, it also happens with the employee db:

```
DB Context Rules for Entities loaded with 2 schemas and 20 tables from Entities-rules.json
Candidate Naming Service resolved DB Context Rules for Entities with 2 schemas
RULED: Column COUNTRY.COUNTRY property name set to COUNTRY1
RULED: Column COUNTRY.CURRENCY property name set to CURRENCY
RULED: Table COUNTRY mapped to entity name COUNTRY
RULED: Table COUNTRY mapped to DbSet name COUNTRY
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: An item with the same key has already been added. Key: COUNTRY
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at EntityFrameworkRuler.Design.Services.Models.DbContextRuleNode.Map(EntityTypeBuilder entityTypeBuilder, EntityRuleNode entityRule)
   at EntityFrameworkRuler.Design.Services.Models.EntityRuleNode.MapTo(EntityTypeBuilder builder, DatabaseTableNode databaseTable)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.ApplyEntityRules(ModelBuilder modelBuilder, EntityTypeBuilder entityTypeBuilder, DatabaseTable table, EntityRuleNode entityRuleNode)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.VisitTable(ModelBuilder modelBuilder, DatabaseTable table, Func`1 baseCall)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.Castle.DynamicProxy.IInterceptor.Intercept(IInvocation invocation)
```

**Comment by R4ND3LL** [comment]
> Candidate Naming Service resolved DB Context Rules for Entities with 2 schemas

I suspect your json file now has 2 schemas with the Name "".   

When you run the scaffolding, EFR will update the json and populate the file with found entities. Meaning even if you start with a blank json, it will populate it fully with all entities so that you can modify later as necessary.

So either regenerate the json from EDMX (and rename the schema again), or nuke the second schema.

**Comment by R4ND3LL** [comment]
By the way, if you try the [Visual Studio extension](https://marketplace.visualstudio.com/items?itemName=Randell.EF-Ruler) then the UI editor would have caught this duplicating naming issue and prevented the change.

**Comment by MagicAndre1981** [comment]
> > Candidate Naming Service resolved DB Context Rules for Entities with 2 schemas
> 
> I suspect your json file now has 2 schemas with the Name "".

yes, because of the table not found issue, I added the option to include unknown schemas, this generated 2 schemas and if I rename firebird to empty I get 2 schemas with empty name which triggers the error.

Thanks for the help and your tool.
