### ISSUE TITLE
Best approach to debugging

### ISSUE THREAD

**Issue by jdlegan** [R4ND3LL/EdmxRuler#29]
Randell,

I was on vacation for a week and am just getting back to this. The last change you made allowed the test database to work flawlessly with the abbreviated TPT setup. I then applied to the production database and again was working flawlessly. I then hit a snag. Although we have performed multiple schema compares, using the sample database as an example, if there were twenty different types of trucks, 19 of them work as expected with 20th throwing an exception (below). I am looking for the best method debug it locally so I can figure out what it is asserting is null when the exception is thrown. For reference, everything generates correctly (for the entire database) with all TPT relationships setup, which numbers over fifty and even the tables that are throwing the exception generate correctly provided that final base type is not set so whatever is happen is subtle and schema comparisons have not yield results. 

If you can provide direction on the best/easiest way to debug this I would appreciate it. Whatever I find I will provide back to you and if it can be fixed in the tool I will fork and create a PR for it. 

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Property(Type propertyType, String propertyName, MemberInfo memberInfo, Nullable`1 typeConfigurationSource, Nullable`1 configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.GetActualProperties(IReadOnlyList`1 properties, Nullable`1 configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalIndexBuilder.Attach(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.PropertiesSnapshot.Attach(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.HasBaseType(EntityType baseEntityType, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.HasBaseType(String baseEntityTypeName, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder.HasBaseType(String name)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.ApplyEntityRules(ModelBuilder modelBuilder, EntityTypeBuilder entityTypeBuilder, DatabaseTable table, EntityRuleNode entityRuleNode)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.VisitTable(ModelBuilder modelBuilder, DatabaseTable table, Func`1 baseCall)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.Castle.DynamicProxy.IInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.RelationalScaffoldingModelFactoryProxy.VisitTable(ModelBuilder modelBuilder, DatabaseTable table)
   at InvokeStub_RelationalScaffoldingModelFactory.VisitTable(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.InvokeVisitTable(ModelBuilder modelBuilder, DatabaseTable table)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.<VisitTables>g__DoInvokeVisitTable|40_0(ScaffoldedTableTrackerItem table, EntityRuleNode entityRule, <>c__DisplayClass40_0&)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.VisitTables(ModelBuilder modelBuilder, ICollection`1 tables)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.Castle.DynamicProxy.IInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.RelationalScaffoldingModelFactoryProxy.VisitTables(ModelBuilder modelBuilder, ICollection`1 tables)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel)
   at Castle.Proxies.RelationalScaffoldingModelFactoryProxy.VisitDatabaseModel_callback(ModelBuilder modelBuilder, DatabaseModel databaseModel)
   at Castle.Proxies.Invocations.RelationalScaffoldingModelFactory_VisitDatabaseModel.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.<>c__DisplayClass75_0.<Castle.DynamicProxy.IInterceptor.Intercept>g__BaseCall|2()
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel, Func`1 baseCall)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.Castle.DynamicProxy.IInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.RelationalScaffoldingModelFactoryProxy.VisitDatabaseModel(ModelBuilder modelBuilder, DatabaseModel databaseModel)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.RelationalScaffoldingModelFactory.Create(DatabaseModel databaseModel, ModelReverseEngineerOptions options)
   at Castle.Proxies.RelationalScaffoldingModelFactoryProxy.Create_callback(DatabaseModel databaseModel, ModelReverseEngineerOptions options)
   at Castle.Proxies.Invocations.RelationalScaffoldingModelFactory_Create.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.<>c__DisplayClass75_0.<Castle.DynamicProxy.IInterceptor.Intercept>g__BaseCall|7(DatabaseModel databaseModel, ModelReverseEngineerOptions options2)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.Create(DatabaseModel databaseModel, ModelReverseEngineerOptions ops, Func`3 baseCall)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.Castle.DynamicProxy.IInterceptor.Intercept(IInvocation invocation)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.RelationalScaffoldingModelFactoryProxy.Create(DatabaseModel databaseModel, ModelReverseEngineerOptions options)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.Create(DatabaseModel databaseModel, ModelReverseEngineerOptions ops)
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at EntityFrameworkRuler.Design.Services.RuledReverseEngineerScaffolder.ScaffoldModel(String connectionString, DatabaseModelFactoryOptions databaseOptions, ModelReverseEngineerOptions modelOptions, ModelCodeGenerationOptions codeOptions)
   at Microsoft.EntityFrameworkCore.Design.Internal.DatabaseOperations.ScaffoldContext(String provider, String connectionString, String outputDir, String outputContextDir, String dbContextClassName, IEnumerable`1 schemas, IEnumerable`1 tables, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContextImpl(String provider, String connectionString, String outputDir, String outputDbContextDir, String dbContextClassName, IEnumerable`1 schemaFilters, IEnumerable`1 tableFilters, String modelNamespace, String contextNamespace, Boolean useDataAnnotations, Boolean overwriteFiles, Boolean useDatabaseNames, Boolean suppressOnConfiguring, Boolean noPluralize)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.ScaffoldContext.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Exception has been thrown by the target of an invocation.
```

**Comment by jdlegan** [comment]
@R4ND3LL, do you have any thoughts on how best to approach debugging this?

**Comment by R4ND3LL** [comment]
I'm also just returning from vacation.    The debugging approach is fairly simple.  

After cloning, open the EntityFrameworkRuler solution and add your existing net core EF project under the Test folder.  Delete the EFR nuget reference(s), then add a direct project reference to EntityFrameworkRuler.Design.

In one of the top level .cs files in your EF project, add the following line at the top:
```CSharp
[assembly: DesignTimeServicesReference("EntityFrameworkRuler.Design.RuledDesignTimeServices, EntityFrameworkRuler.Design")]
```

Then just run your scaffolding command as usual from the terminal.  As long as you are in DEBUG mode, you will hit an entry breakpoint in the EFR.Design project as the debugger is launched.  Ensure your IDE has enabled "break on exceptions" so you can just run until the error occurs.  

Do you use Rider or VS?

**Comment by jdlegan** [comment]
Thank you. The `DesignTimeServicesReference` is what I was missing. 

I tried to work through it using the MS EF Core libraries symbols but I still cannot get to the property that it is throwing on. Below is a little bit more details but nothing that was not already known, which is the failure occurring while establishing the relationship with the two tables previously mentioned, it enumerating the properties of the base table for the last table in the TPT chain (for only this one relationship) and it throwing on a null check. My next step is to grab the EF Core source and get the locals in that method where the exceptions is occurring. Interestingly enough, with Just My Code disabled and symbols properly loaded for the EF Core libs, something is detaching the debugger before reaching the call where the exception occurs. Even manually loading the symbols after the fact, after the exception occurs and VS has broken in, it is still not happy. I went as far as the remove the multi-targeting, targeting only net7 and brought EF Core forward to the last version before they made breaking changes in the `Microsoft.EntityFrameworkCore.Design.Internal` namespace (7.0.9 IIRC) and still cannot get what I need so grabbing the EF Core lib source is next. Below is what I pulled out of the base type and type extending it (debug long view) in case anything jumps out at you as useful. The interesting piece to all of this is that this TPT structure exists in seven different schema, with each scheme being vendor specific with a base common schema that contains the base and first TPT table. All other six schemas work as expected. There is nothing different with respect to the TPT relationship in this last schema, indexes, FK's and PK's are all the same as the other six schemas. Further, if I take one of the same level TPT tables (last one in the chain, the one that is failing here) and extend this schema's table, it works correctly. If I do not establish the relationship at all in the tool (Base Type), the model builds correctly, but without being TPT modeled of course. I was working on the theory that there was some overlapping column name, possibly with a different data type or nullable vs non-nullable, but I ruled that out with some creative SQL queries comparing column names, data types, precision and nullability along all of those trees across all schemas and everything came back as clean. 

I will keep you posted on my findings. Thank you again for the help. 
```
Exception thrown at             

if (baseName.HasNonWhiteSpace()) entityTypeBuilder.HasBaseType(baseName);

DebugView (Long) of entity type throwing the exception on call to entityBuilder.HasBaseType()

EntityType: XyzPlasticCardTransactionsEntity (Dictionary<string, object>) Base: XyzCardTransactionsEntity (Dictionary<string, object>) CLR Type: Dictionary<string, object>
  Properties: 
    ActivationIndicator (no field, string) Indexer MaxLength(1) Ansi
      Annotations: 
        MaxLength: 1
        Relational:ColumnName: ActivationIndicator
        Relational:ColumnOrder: 2
        Relational:IsFixedLength: True
        Unicode: False
    AuthAcquirerId (no field, string) Indexer MaxLength(20) Ansi
      Annotations: 
        MaxLength: 20
        Relational:ColumnName: AuthAcquirerId
        Relational:ColumnOrder: 15
        Unicode: False
    AuthAmount (no field, decimal?) Indexer
      Annotations: 
        Relational:ColumnName: AuthAmount
        Relational:ColumnOrder: 22
        Relational:ColumnType: decimal(19, 4)
    AuthPaymentFacilitator (no field, string) Indexer MaxLength(11) Ansi
      Annotations: 
        MaxLength: 11
        Relational:ColumnName: AuthPaymentFacilitator
        Relational:ColumnOrder: 20
        Unicode: False
    AuthorizationMerchantNumber (no field, string) Indexer MaxLength(20)
      Annotations: 
        MaxLength: 20
        Relational:ColumnName: AuthorizationMerchantNumber
        Relational:ColumnOrder: 5
    ClearedTransmissionDate (no field, DateTime?) Indexer
      Annotations: 
        Relational:ColumnName: ClearedTransmissionDate
        Relational:ColumnOrder: 17
    ClearingAcquirerId (no field, string) Indexer MaxLength(20) Ansi
      Annotations: 
        MaxLength: 20
        Relational:ColumnName: ClearingAcquirerId
        Relational:ColumnOrder: 14
        Unicode: False
    ClearingPaymentFacilitator (no field, string) Indexer MaxLength(11) Ansi
      Annotations: 
        MaxLength: 11
        Relational:ColumnName: ClearingPaymentFacilitator
        Relational:ColumnOrder: 21
        Unicode: False
    ContactlessIndicator (no field, string) Indexer MaxLength(1) Ansi
      Annotations: 
        MaxLength: 1
        Relational:ColumnName: ContactlessIndicator
        Relational:ColumnOrder: 3
        Relational:IsFixedLength: True
        Unicode: False
    DeviceName (no field, string) Indexer MaxLength(20)
      Annotations: 
        MaxLength: 20
        Relational:ColumnName: DeviceName
        Relational:ColumnOrder: 19
    DeviceType (no field, string) Indexer MaxLength(25) Ansi
      Annotations: 
        MaxLength: 25
        Relational:ColumnName: DeviceType
        Relational:ColumnOrder: 18
        Unicode: False
    MerchantAcceptorDomesticTaxId (no field, string) Indexer MaxLength(20)
      Annotations: 
        MaxLength: 20
        Relational:ColumnName: MerchantAcceptorDomesticTaxId
        Relational:ColumnOrder: 10
    MerchantCategoryCode (no field, string) Indexer MaxLength(10) Ansi
      Annotations: 
        MaxLength: 10
        Relational:ColumnName: MerchantCategoryCode
        Relational:ColumnOrder: 7
        Unicode: False
    MerchantCountryCode (no field, string) Indexer MaxLength(3)
      Annotations: 
        MaxLength: 3
        Relational:ColumnName: MerchantCountryCode
        Relational:ColumnOrder: 8
    MerchantLoopCode (no field, string) Indexer MaxLength(20)
      Annotations: 
        MaxLength: 20
        Relational:ColumnName: MerchantLoopCode
        Relational:ColumnOrder: 11
    MerchantName (no field, string) Indexer Index MaxLength(100)
      Annotations: 
        MaxLength: 100
        Relational:ColumnName: MerchantName
        Relational:ColumnOrder: 6
    MerchantNumber (no field, string) Indexer MaxLength(20)
      Annotations: 
        MaxLength: 20
        Relational:ColumnName: MerchantNumber
        Relational:ColumnOrder: 4
    MerchantPostCode (no field, string) Indexer MaxLength(10)
      Annotations: 
        MaxLength: 10
        Relational:ColumnName: MerchantPostCode
        Relational:ColumnOrder: 9
    MerchantRetailer (no field, string) Indexer MaxLength(20)
      Annotations: 
        MaxLength: 20
        Relational:ColumnName: MerchantRetailer
        Relational:ColumnOrder: 12
    StoreId (no field, string) Indexer MaxLength(20) Ansi
      Annotations: 
        MaxLength: 20
        Relational:ColumnName: StoreId
        Relational:ColumnOrder: 13
        Unicode: False
    TerminalNumber (no field, string) Indexer MaxLength(20)
      Annotations: 
        MaxLength: 20
        Relational:ColumnName: TerminalNumber
        Relational:ColumnOrder: 16
  Indexes: 
    MerchantName NIX_MerchantName
  Annotations: 
    Relational:Schema: XYZ
    Relational:TableName: PlasticCardTransactions
    Scaffolding:DbSetName: XyzPlasticCardTransactionsEntities

Base type

EntityType: XyzCardTransactionsEntity (Dictionary<string, object>) Base: CardTransactionsEntity (Dictionary<string, object>) CLR Type: Dictionary<string, object>
  Properties: 
    AcceptanceMatchingProfileId (no field, int?) Indexer
      Annotations: 
        Relational:ColumnName: AcceptanceMatchingProfileId
        Relational:ColumnOrder: 19
    AcceptanceMethodId (no field, int?) Indexer
      Annotations: 
        Relational:ColumnName: AcceptanceMethodId
        Relational:ColumnOrder: 18
    AcceptorNameLocSubField1 (no field, string) Indexer MaxLength(100)
      Annotations: 
        MaxLength: 100
        Relational:ColumnName: AcceptorNameLocSubField1
        Relational:ColumnOrder: 31
    AcceptorNameLocSubField2 (no field, string) Indexer MaxLength(100)
      Annotations: 
        MaxLength: 100
        Relational:ColumnName: AcceptorNameLocSubField2
        Relational:ColumnOrder: 32
    AcceptorNameLocSubField3 (no field, string) Indexer MaxLength(100)
      Annotations: 
        MaxLength: 100
        Relational:ColumnName: AcceptorNameLocSubField3
        Relational:ColumnOrder: 33
    Amount (no field, decimal?) Indexer
      Annotations: 
        Relational:ColumnName: Amount
        Relational:ColumnOrder: 2
        Relational:ColumnType: decimal(19, 4)
    AmountBalance (no field, decimal?) Indexer
      Annotations: 
        Relational:ColumnName: AmountBalance
        Relational:ColumnOrder: 15
        Relational:ColumnType: decimal(19, 4)
    AmountBeforeFees (no field, decimal?) Indexer
      Annotations: 
        Relational:ColumnName: AmountBeforeFees
        Relational:ColumnOrder: 14
        Relational:ColumnType: decimal(19, 4)
    AuthorizationCode (no field, string) Indexer MaxLength(50) Ansi
      Annotations: 
        MaxLength: 50
        Relational:ColumnName: AuthorizationCode
        Relational:ColumnOrder: 21
        Unicode: False
    AuthorizationFlagId (no field, int?) Indexer
      Annotations: 
        Relational:ColumnName: AuthorizationFlagId
        Relational:ColumnOrder: 6
    CardBatchName (no field, string) Indexer MaxLength(50)
      Annotations: 
        MaxLength: 50
        Relational:ColumnName: CardBatchName
        Relational:ColumnOrder: 25
    CardDesignCode (no field, string) Indexer MaxLength(40)
      Annotations: 
        MaxLength: 40
        Relational:ColumnName: CardDesignCode
        Relational:ColumnOrder: 24
    Cleared (no field, string) Indexer MaxLength(1) Ansi
      Annotations: 
        MaxLength: 1
        Relational:ColumnName: Cleared
        Relational:ColumnOrder: 10
        Relational:IsFixedLength: True
        Unicode: False
    ClearedDateTime (no field, DateTime?) Indexer
      Annotations: 
        Relational:ColumnName: ClearedDateTime
        Relational:ColumnOrder: 35
    CreatedDateTime (no field, DateTime?) Indexer
      Annotations: 
        Relational:ColumnName: CreatedDateTime
        Relational:ColumnOrder: 34
    CurrencyAlpha (no field, string) Indexer MaxLength(3) Ansi
      Annotations: 
        MaxLength: 3
        Relational:ColumnName: CurrencyAlpha
        Relational:ColumnOrder: 13
        Unicode: False
    CurrencyCode (no field, string) Indexer MaxLength(3)
      Annotations: 
        MaxLength: 3
        Relational:ColumnName: CurrencyCode
        Relational:ColumnOrder: 12
    Gldata (no field, string) Indexer MaxLength(500) Ansi
      Annotations: 
        MaxLength: 500
        Relational:ColumnName: GLData
        Relational:ColumnOrder: 37
        Unicode: False
    InterchangeAmount (no field, decimal?) Indexer
      Annotations: 
        Relational:ColumnName: InterchangeAmount
        Relational:ColumnOrder: 38
        Relational:ColumnType: decimal(19, 4)
    LocalAmount (no field, decimal?) Indexer
      Annotations: 
        Relational:ColumnName: LocalAmount
        Relational:ColumnOrder: 40
        Relational:ColumnType: decimal(19, 4)
    LocalCurrency (no field, string) Indexer MaxLength(3) Ansi
      Annotations: 
        MaxLength: 3
        Relational:ColumnName: LocalCurrency
        Relational:ColumnOrder: 39
        Unicode: False
    LocalDateTime (no field, DateTime?) Indexer
      Annotations: 
        Relational:ColumnName: LocalDateTime
        Relational:ColumnOrder: 36
    NotificationReference (no field, string) Indexer MaxLength(30) Ansi
      Annotations: 
        MaxLength: 30
        Relational:ColumnName: NotificationReference
        Relational:ColumnOrder: 7
        Unicode: False
    OriginalTransactionId (no field, string) Indexer Index MaxLength(30) Ansi
      Annotations: 
        MaxLength: 30
        Relational:ColumnName: OriginalTransactionId
        Relational:ColumnOrder: 8
        Unicode: False
    ReasonText (no field, string) Indexer MaxLength(200)
      Annotations: 
        MaxLength: 200
        Relational:ColumnName: ReasonText
        Relational:ColumnOrder: 22
    RelatedTransactionId (no field, string) Indexer MaxLength(30) Ansi
      Annotations: 
        MaxLength: 30
        Relational:ColumnName: RelatedTransactionId
        Relational:ColumnOrder: 27
        Unicode: False
    ResultCode (no field, string) Indexer MaxLength(20)
      Annotations: 
        MaxLength: 20
        Relational:ColumnName: ResultCode
        Relational:ColumnOrder: 30
    RetrievalReferenceNumber (no field, string) Indexer MaxLength(30) Ansi
      Annotations: 
        MaxLength: 30
        Relational:ColumnName: RetrievalReferenceNumber
        Relational:ColumnOrder: 16
        Unicode: False
    Reversed (no field, byte?) Indexer
      Annotations: 
        Relational:ColumnName: Reversed
        Relational:ColumnOrder: 28
    Scheme (no field, string) Indexer MaxLength(20)
      Annotations: 
        MaxLength: 20
        Relational:ColumnName: Scheme
        Relational:ColumnOrder: 11
    SchemeTransactionReferenceNumber (no field, string) Indexer MaxLength(30)
      Annotations: 
        MaxLength: 30
        Relational:ColumnName: SchemeTransactionReferenceNumber
        Relational:ColumnOrder: 29
    TokenTypeId (no field, int?) Indexer
      Annotations: 
        Relational:ColumnName: TokenTypeId
        Relational:ColumnOrder: 20
    TransactionOriginCode (no field, string) Indexer MaxLength(20)
      Annotations: 
        MaxLength: 20
        Relational:ColumnName: TransactionOriginCode
        Relational:ColumnOrder: 23
    TransactionReferenceNumber (no field, string) Indexer MaxLength(30) Ansi
      Annotations: 
        MaxLength: 30
        Relational:ColumnName: TransactionReferenceNumber
        Relational:ColumnOrder: 17
        Unicode: False
    TransactionResultId (no field, int?) Indexer
      Annotations: 
        Relational:ColumnName: TransactionResultId
        Relational:ColumnOrder: 5
    TransactionTypeNameId (no field, int?) Indexer
      Annotations: 
        Relational:ColumnName: TransactionTypeNameId
        Relational:ColumnOrder: 3
    TransactionUniqueId (no field, string) Indexer MaxLength(36) Ansi
      Annotations: 
        MaxLength: 36
        Relational:ColumnName: TransactionUniqueId
        Relational:ColumnOrder: 9
        Unicode: False
    WalletServiceProviderId (no field, int?) Indexer
      Annotations: 
        Relational:ColumnName: WalletServiceProviderId
        Relational:ColumnOrder: 26
  Indexes: 
    ProcessorTypeId IX_NCI_CardTransactions_ProcessorTypeId
    OriginalTransactionId NIX_OriginalTransactionId
  Annotations: 
    Relational:Schema: XYZ
    Relational:TableName: CardTransactions
    Scaffolding:DbSetName: XyzCardTransactionsEntities



System.InvalidOperationException
  HResult=0x80131509
  Message=Nullable object must have a value.
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_NoValue()
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.Property(Type propertyType, String propertyName, MemberInfo memberInfo, Nullable`1 typeConfigurationSource, Nullable`1 configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.GetActualProperties(IReadOnlyList`1 properties, Nullable`1 configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalIndexBuilder.Attach(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.PropertiesSnapshot.Attach(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.HasBaseType(EntityType baseEntityType, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalEntityTypeBuilder.HasBaseType(String baseEntityTypeName, ConfigurationSource configurationSource)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder.HasBaseType(String name)
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.ApplyEntityRules(ModelBuilder modelBuilder, EntityTypeBuilder entityTypeBuilder, DatabaseTable table, EntityRuleNode entityRuleNode) in C:\git\rec\EntityFrameworkRuler\src\EntityFrameworkRuler.Design\Services\RuledRelationalScaffoldingModelFactory.cs:line 624
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.VisitTable(ModelBuilder modelBuilder, DatabaseTable table, Func`1 baseCall) in C:\git\rec\EntityFrameworkRuler\src\EntityFrameworkRuler.Design\Services\RuledRelationalScaffoldingModelFactory.cs:line 570
   at EntityFrameworkRuler.Design.Services.RuledRelationalScaffoldingModelFactory.Castle.DynamicProxy.IInterceptor.Intercept(IInvocation invocation) in C:\git\rec\EntityFrameworkRuler\src\EntityFrameworkRuler.Design\Services\RuledRelationalScaffoldingModelFactory.cs:line 2007
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.RelationalScaffoldingModelFactoryProxy.VisitTable(ModelBuilder modelBuilder, DatabaseTable table)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)```

**Comment by R4ND3LL** [comment]
While I understand the obstacle of dealing with intellectual property here, if I had a copy of the DB schema (no data necessary) that was complete enough to reproduce the issue, then I'm sure I could identify the problem.  If you're game, I can share my email so that you can send it directly rather than posting it to the public github issue.     Github really needs a PM option.

That said, I have debugged the EF source also, though I'm not sure off hand the best advice for setting that up (I dont recall exactly what I did with the environment to get it started).    Alternatively, with jetbrains Rider, you can enable debugging external sources.  Then on the exception break point, you can walk to the head of the stack and it will automatically decompile sources and allow for more inspections.  I think the latest VS version has something similar based on what I read.
